palavras_positivas = ['abba', 'capacidade', 'mencionado acima', 'absoluto', 'absolvição', 'absorvido', 'abundância',
                      'abundante', 'acadêmico', 'academia', 'aceitável', 'aceitação', 'acessível', 'elogio',
                      'acomodação', 'acompanhamento', 'realizar', 'realizado', 'realização', 'acordo',
                      'prestação de contas', 'responsável', 'acreditado', 'accueil', 'exato', 'ás', 'alcançar',
                      'realização', 'reconhecimento', 'adquirir', 'aquisição', 'acrobata', 'açao', 'real', 'acuidade',
                      'perspicácia', 'adaptar', 'adaptável', 'endereços', 'perito', 'adequação', 'adjunto', 'admirável',
                      'almirante', 'admiração', 'admirar',
                      'admirador', 'admissível', 'adorável', 'adoração', 'adorar', 'avançar', 'avançado', 'avanço',
                      'vantagem', 'vantajoso', 'advento', 'aventura', 'aventuroso', 'aconselhável', 'aconselhar',
                      'conselheiro', 'advocacia', 'estético', 'estética', 'afável', 'afeição', 'afiliado', 'afirmar',
                      'afirmação', 'afirmativo', 'afirmativamente', 'afluência', 'afluente', 'proporcionar', 'aga',
                      'ágil',
                      'agilidade', 'concordar', 'agradável', 'combinado', 'concordando', 'acordo', 'agricultura',
                      'à frente',
                      'ajuda', 'auxiliando', 'alabastro', 'estado de alerta', 'alimentação', 'vivo', 'acalmar',
                      'fidelidade',
                      'allegro', 'aliviar', 'alívio', 'aliado', 'admissível', 'fascinação', 'sedutor', 'aliado',
                      'onipotente', 'aloha', 'incrivelmente', 'embaixador', 'ambição', 'melhorar', 'amém', 'dócil',
                      'emendar', 'reparação', 'amenidade', 'amável', 'amigável', 'anistia', 'amour', 'divertir',
                      'divertido',
                      'divertimento', 'divertido', 'analista', 'âncora', 'ancoragem', 'anjo', 'angélico', 'animar',
                      'animado', 'antibióticos', 'antídoto', 'antifúngica', 'antiguidade', 'antisséptico', 'aprumo',
                      'apologético', 'desculpar', 'desculpa', 'apóstolo', 'aplauso', 'valorização', 'aprovação',
                      'aprovação',
                      'aprovar', 'que aprova', 'apto', 'aptidão', 'arqueologia', 'ardente', 'ardor', 'aristocracia',
                      'aristocrático', 'armado', 'armadura', 'aroma', 'despertar', 'ordem', 'arte', 'articular',
                      'articulação', 'artesão', 'artista', 'artístico', 'ascendência', 'subida', 'aspiração', 'aspirar',
                      'aspirador', 'montagem', 'assentimento', 'afirmando', 'ativos', 'auxiliar', 'assistência',
                      'associado',
                      'amenizar', 'garantia', 'seguro', 'espantosamente', 'assombro', 'astrólogo', 'astronauta',
                      'astrônomo',
                      'astuto', 'atleta', 'atlético', 'átomo', 'expiar', 'expiação', 'acessório', 'atingível',
                      'realização',
                      'assistente', 'atenção', 'atencioso', 'atestar', 'advogado', 'atração', 'atratividade',
                      'aumentar',
                      'agosto', 'tia', 'aura', 'auspicioso', 'autêntico', 'autenticidade', 'autor', 'oficial',
                      'autoridade',
                      'autorização', 'autorizado', 'avatar', 'prêmio', 'ay', 'sim', 'bebê', 'bacharelado',
                      'espinha dorsal',
                      'equilíbrio', 'equilibrado', 'balada', 'balé', 'cédula', 'bálsamo', 'bálsamo', 'banquete',
                      'batismo',
                      'batismal', 'bardo', 'barganha', 'basquete', 'bastião', 'banho', 'viga', 'radiante',
                      'embelezamento',
                      'bonita', 'embelezar', 'beleza', 'base rochosa', 'cerveja', 'condizente', 'ajudar', 'crente',
                      'benfeitor', 'benéfico', 'benefício', 'benevolência', 'benigno', 'ancoradouro', 'desposada',
                      'aperfeiçoamento', 'bebida', 'bíblico', 'bilíngüe', 'nascimento', 'aniversário', 'sem culpa',
                      'abençoar', 'abençoado', 'bênção', 'bênçãos', 'felicidade', 'bem-aventurado', 'sem sangue',
                      'flor',
                      'flor', 'ostentação', 'guarda costas', 'violento', 'negrito', 'ousadia', 'apoiar', 'prosperidade',
                      'bonne', 'bônus', 'estudioso', 'livraria', 'traça', 'bênção', 'caridoso', 'recompensa', 'buquê',
                      'miolos', 'bravura', 'café da manhã', 'nupcial', 'noiva', 'noivo', 'dama de honra', 'clarear',
                      'brilho', 'brilhante', 'brocado', 'irmão', 'fraternidade', 'fraternal', 'pinote', 'camarada',
                      'construir', 'construção', 'buldogue', 'à prova de bala', 'bóia', 'beijo', 'mordomo',
                      'amanteigado',
                      'rechonchudo', 'zumbido', 'táxi', 'armário', 'café', 'calculadora', 'bezerro', 'calma', 'canário',
                      'cândido', 'candidato', 'cristalizado', 'capitalista', 'capitão', 'cativar', 'cativante',
                      'carreira',
                      'cuidadoso', 'cuidadosamente', 'carícia', 'zelador', 'Carol', 'cascata', 'dinheiro', 'categórico',
                      'fornecer', 'catártico', 'catedral', 'cauteloso', 'cautelosamente', 'célebre', 'a comemorar',
                      'celebração', 'celebridade', 'celestial', 'centro', 'centurião', 'cerebral', 'cerimônia',
                      'segurança',
                      'presidente', 'presidenta', 'campeão', 'cântico', 'carregador', 'caridoso', 'caridade', 'encanto',
                      'Encantado', 'charmoso', 'castidade', 'tagarelando', 'check list', 'alegria', 'alegre', 'alegria',
                      'aplauso', 'alegre', 'químico', 'acalentar', 'cereja', 'chefe', 'criança', 'infância', 'gorjeio',
                      'cinzel', 'cavalheirismo', 'chocolate', 'escolha', 'coro', 'coral', 'coro', 'escolhido',
                      'sopa grossa',
                      'crônica', 'cacarejar', 'igreja', 'cidra', 'circuncisão', 'evasão', 'cidadão', 'civil',
                      'civilidade',
                      'civilização', 'civilizado', 'clarividente', 'aplaudir', 'esclarecer', 'clássico', 'clássico',
                      'clássicos', 'classificar', 'limpo', 'limpeza', 'limpeza', 'limpo', 'limpar', 'limpeza',
                      'liberação',
                      'clareza', 'clerical', 'inteligente', 'inteligência', 'clímax', 'proximidade', 'encerramento',
                      'vestir', 'palhaço', 'aliança', 'costa', 'coexiste', 'convincente', 'cognitivo', 'coerência',
                      'coerente', 'coesivo', 'coletivamente', 'coronel', 'colossal', 'conforto', 'comandante',
                      'dominante',
                      'comemorar', 'comemoração', 'comemorativo', 'recomendar', 'louvável', 'comentarista',
                      'comprometido',
                      'comodoro', 'comunidade', 'comunicar', 'comunicativo', 'comunhão', 'comunidade', 'comutação',
                      'comutar', 'companheiro', 'compaixão', 'compassivo', 'compatibilidade', 'compatível', 'atraente',
                      'compensar', 'compensatório', 'competência', 'competência', 'competente', 'complacência',
                      'complemento', 'complementar', 'completamente', 'perfeição', 'completando', 'realização',
                      'conformidade', 'compatível', 'cumplicidade', 'elogio', 'composto', 'compositor', 'compostura',
                      'compreender', 'abrangente', 'camarada', 'concêntrico', 'conciliação', 'concluindo', 'concórdia',
                      'concordância', 'pêsames', 'perdoar', 'conducente', 'condutividade', 'confederado', 'confessar',
                      'confiança', 'confiante', 'confirmado', 'conformidade', 'agradável', 'congratulatório',
                      'congregação',
                      'congruência', 'conhecedor', 'consciência', 'consciencioso', 'consciência', 'consagração',
                      'conservação', 'conservar', 'considerável', 'atencioso', 'consistência', 'console', 'consoante',
                      'constância', 'constante', 'constitucional', 'construir', 'consumado', 'contato', 'contemplação',
                      'conteúdo', 'continuar', 'contorno', 'contribuir', 'contribuidor', 'conveniência', 'conveniente',
                      'convento', 'convenção', 'familiarizado', 'conversação', 'converter', 'convencer', 'legal',
                      'frieza',
                      'cooperar', 'cooperando', 'cooperação', 'cooperativo', 'testemunho', 'coroação', 'corporação',
                      'corpóreo', 'corretivo', 'correspondência', 'corroborar', 'cosmopolita', 'acolhedor', 'conselho',
                      'conselho', 'conselheiro', 'contagem', 'condessa', 'coragem', 'corajoso', 'cortês', 'cortesia',
                      'namoro', 'enseada', 'pacto', 'berço', 'ofício', 'artesão', 'creme', 'crio', 'criativo',
                      'crédito',
                      'credencial', 'credibilidade', 'acreditável', 'crédito', 'honroso', 'creditada', 'crescendo',
                      'crítica', 'coroação', 'crucial', 'cristal', 'chamego', 'culinária', 'culminação', 'cultivar',
                      'cultivado', 'cultivo', 'cultura', 'astuto', 'curável', 'curiosidade', 'ondulação', 'almofada',
                      'cliente', 'fofa', 'Cortadores', 'dama', 'dança', 'ousado', 'querido', 'arrojado', 'filha',
                      'amanhecer', 'Combinado', 'caro', 'debate', 'decência', 'decente', 'declaratório', 'dedicação',
                      'defender', 'defendeu', 'defensor', 'defender', 'defesa', 'deferência', 'definitivo', 'grau',
                      'deleitável', 'delegado', 'deliberado', 'delicioso', 'delícia', 'Encantado', 'delicioso',
                      'libertação',
                      'entrega', 'democracia', 'demonstrável', 'demonstrativo', 'dependente', 'profundidade',
                      'descritivo',
                      'merecer', 'merecia', 'desenhista', 'desejável', 'desejando', 'desejoso', 'destino', 'descobrir',
                      'detecção', 'determinação', 'determinado', 'desenvolver', 'devoto', 'devoto', 'destreza',
                      'diamante',
                      'diário', 'dicionário', 'didático', 'dietético', 'digno', 'dignidade', 'diligência', 'jantar',
                      'diplomacia', 'diplomático', 'diretor', 'descoberta', 'discreto', 'discrição', 'discricionário',
                      'discussão', 'desinfecção', 'disposto', 'disseminar', 'destilação', 'distinção', 'cantiga',
                      'diverso',
                      'diversificado', 'desvio', 'divindade', 'médico', 'executor', 'obstinado', 'golfinho', 'dominar',
                      'dom', 'doação', 'indubitavelmente', 'pomba', 'aveludado', 'dueto', 'duque', 'durabilidade',
                      'durável',
                      'obediente', 'ansioso', 'ânsia', 'conde', 'ganhar', 'sério', 'seriamente', 'seriedade',
                      'facilidade',
                      'servidão', 'maleável', 'comer', 'êxtase', 'extático', 'edificação', 'educar', 'educado',
                      'educacional', 'eficaz', 'eficácia', 'eficiência', 'eficiente', 'esforço', 'ejaculação',
                      'elaboração',
                      'exultante', 'mais velho', 'anciãos', 'eleito', 'elétrico', 'eletricidade', 'elegância',
                      'elegante',
                      'elevação', 'elegível', 'elite', 'eloquência', 'eloquente', 'elucidar', 'libertação', 'abraçar',
                      'emérito', 'eminência', 'eminente', 'eminentemente', 'emir', 'empatia', 'autorizar', 'emular',
                      'habilitar', 'capacitação', 'encantar', 'enchanted', 'encantador', 'bis', 'encorajar',
                      'encorajamento',
                      'enciclopédia', 'esforçar-se', 'interminável', 'dotar', 'dotado', 'doação', 'resistência',
                      'suportar',
                      'enérgico', 'fazer cumprir', 'contratado', 'atraente', 'aumentar', 'apreciar', 'desfrutando',
                      'iluminar', 'iluminação', 'animar', 'enriquecer', 'conjunto', 'estandarte', 'empreendedor',
                      'entreter',
                      'entretido', 'divertido', 'diversão', 'entusiasmo', 'entusiasta', 'environ', 'efemérides',
                      'épico',
                      'epítome', 'igualdade', 'igualmente', 'equilíbrio', 'capital próprio', 'erótico', 'incumbência',
                      'erudito', 'fuga', 'espírito', 'essencial', 'estabelecido', 'estima', 'estético', 'ético',
                      'ética',
                      'sempre-viva', 'eterno', 'evidente', 'evolução', 'exaltar', 'exaltação', 'exaltado',
                      'ultrapassarem',
                      'sobressair', 'excelência', 'excelente', 'troca', 'excitável', 'excitação', 'excitar', 'animado',
                      'excitação', 'emocionante', 'exemplar', 'isenção', 'alegria', 'exortar', 'exortação',
                      'existência',
                      'exótico', 'esperar', 'expectativa', 'expediente', 'expedição', 'experimentado', 'especialista',
                      'perícia', 'explicar', 'requintado', 'requintadamente', 'ampliar', 'extenso', 'extra',
                      'extraordinário', 'desenredar', 'exuberância', 'facilitar', 'Fatos', 'faculdade', 'fain', 'feira',
                      'razoavelmente', 'fé', 'fiel', 'fama', 'familiar', 'familiaridade', 'famoso', 'famosamente',
                      'chique',
                      'fanfarra', 'fascinante', 'fascinação', 'elegante', 'impecável', 'favorável', 'favorito',
                      'favoritismo', 'destemido', 'façanha', 'característica', 'sentindo-me', 'felicidade',
                      'companheiro',
                      'camaradagem', 'feminino', 'fértil', 'fervor', 'festival', 'festivo', 'festa', 'fidelidade',
                      'fiesta',
                      'finalmente', 'enfeite', 'sutileza', 'bola de fogo', 'à prova de fogo', 'firmeza', 'primogênito',
                      'apropriado', 'acessório', 'lisonjeiro', 'frota', 'flexibilidade', 'flerte', 'floral', 'fluxo',
                      'florido', 'rubor', 'vôo', 'foco', 'carinho', 'Comida', 'futebol', 'paciência', 'dianteiro',
                      'antepassados', 'acima expostos', 'capataz', 'precursor', 'prever', 'previsto', 'previdência',
                      'forjar', 'perdoar', 'perdoado', 'indulgente', 'formativo', 'fórmula', 'forte', 'próximo',
                      'fortificar', 'fortitude', 'fortaleza', 'afortunado', 'fortuna', 'para a frente', 'encontrado',
                      'fundação', 'perfumado', 'franco', 'franqueza', 'fraternal', 'liberdade', 'livremente', 'amigos',
                      'afabilidade', 'amigáveis', 'amizade', 'brincalhão', 'brincadeira', 'frugal', 'frutífero',
                      'Preencha',
                      'cumprimento', 'completo', 'totalmente', 'Diversão', 'fundamental', 'fusível', 'fusão', 'ganho',
                      'ganhar', 'valente', 'bravura', 'abundância', 'jardim', 'granada', 'guarnição', 'gazeta',
                      'engrenagem',
                      'jóia', 'geral', 'generosidade', 'generoso', 'genial', 'gênio', 'distinto', 'cavalheiro',
                      'suavidade',
                      'pequena nobreza', 'genuíno', 'gerânio', 'Presente', 'talentoso', 'gigantesco', 'risadinha',
                      'viga',
                      'dando', 'feliz', 'alegria', 'alegria', 'deslize', 'vislumbre', 'cintilante', 'glorificação',
                      'glorificar', 'glória', 'lustro', 'brilho', 'incandescente', 'Deus', 'piedoso', 'dádiva', 'ouro',
                      'Bom', 'considerável', 'bondade', 'bens', 'boa vontade', 'deslumbrante', 'evangelho', 'governar',
                      'graça', 'gracioso', 'gracioso', 'graciosamente', 'graduação', 'netos', 'grandeza', 'avó',
                      'conceder',
                      'concedido', 'grato', 'gratificar', 'gratidão', 'maior', 'grandeza', 'verde', 'saudação',
                      'gregário',
                      'sorriso largo', 'grist', 'areia', 'base', 'crescer', 'crescimento', 'garantia', 'guarda',
                      'guardião',
                      'tutela', 'governamental', 'orientação', 'guia', 'guia', 'guru', 'entranhas', 'ginasta',
                      'habitat',
                      'saudar', 'robusto', 'conveniente', 'felizmente', 'felicidade', 'feliz', 'ousado',
                      'harmoniosamente',
                      'harmonia', 'colheita', 'refúgio', 'progresso', 'curar', 'cicatrização', 'saudável', 'saudável',
                      'sincero', 'lareira', 'cordialmente', 'celestial', 'céus', 'hedonismo', 'peso', 'capacete',
                      'ajudante',
                      'útil', 'de ervas', 'herói', 'heróico', 'heroísmo', 'heroína', 'heroísmo', 'apogeu', 'mais alta',
                      'hilário', 'hilaridade', 'contratar', 'passatempo', 'feriado', 'santidade', 'piedosos',
                      'homenagem',
                      'homologia', 'honesto', 'honestidade', 'mel', 'lua de mel', 'honra', 'honroso', 'esperança',
                      'esperançoso', 'horizonte', 'hospitalidade', 'casa', 'serviço de limpeza', 'abraço', 'humano',
                      'humanitário', 'humanidade', 'humilde', 'humilhado', 'humildemente', 'humildade', 'humorista',
                      'engraçado', 'hurra', 'agricultura', 'silêncio', 'cabana', 'higiênico', 'hino', 'idealismo',
                      'ídolo',
                      'iluminar', 'iluminação', 'ilustrar', 'ilustre', 'imaginativo', 'imaculado', 'imediatamente',
                      'imenso',
                      'imergir', 'imortal', 'imóvel', 'transmitir', 'imparcial', 'imparcialidade', 'impecável',
                      'impenetrável', 'importância', 'importante', 'impressionar', 'impressão', 'melhorar', 'melhorado',
                      'melhoria', 'melhorando', 'improvisar', 'inalienável', 'inauguração', 'incisivo', 'incluir',
                      'incluído', 'Incluindo', 'inclusivo', 'renda', 'aumentar', 'indelével', 'indenização',
                      'independência',
                      'indestrutível', 'individualidade', 'indômito', 'inefável', 'barato', 'infalível', 'infantil',
                      'infiltração', 'infinito', 'infinito', 'influência', 'influente', 'informação', 'engenhoso',
                      'herança',
                      'inimitável', 'inocência', 'inocente', 'inocentemente', 'inócuo', 'inovar', 'inovação',
                      'inquiridor',
                      'inquérito', 'inquisitivo', 'inseparável', 'insígnia', 'inspetor', 'inspiração', 'inspirar',
                      'inspirado', 'instintivo', 'instruir', 'instrução', 'instrutor', 'instrumental', 'segurar',
                      'intacto',
                      'integridade', 'intelecto', 'intelectual', 'inteligência', 'inteligente', 'pretendido', 'intenso',
                      'relações', 'interesse', 'interessado', 'interessante', 'interior', 'interlocutório',
                      'interlúdio',
                      'interminável', 'intervenção', 'íntimo', 'entonação', 'intrépido', 'intuição', 'intuitivo',
                      'invariavelmente', 'inventivo', 'inventor', 'investigar', 'revigorar', 'convite', 'convidar',
                      'convidativo', 'ferro', 'irredutível', 'irrefutável', 'bolada', 'geléia', 'brincadeira',
                      'trabalho',
                      'Junte-se', 'juntou', 'palhaço', 'brincadeira', 'jornalista', 'jornada', 'jovial', 'alegria',
                      'alegre',
                      'alegre', 'jubilante', 'jubileu', 'judicial', 'judicioso', 'saltar', 'justiça', 'justificável',
                      'justificação', 'lembrança', 'ken', 'principal', 'pedra angular', 'tipo', 'bondade', 'parentes',
                      'rei',
                      'beijo', 'gatinho', 'destreza', 'cavaleiro', 'conhecimento', 'conhecimento', 'glória', 'trabalho',
                      'renda', 'Cordeiro', 'terra', 'desembarcou', 'laser', 'louvável', 'riso', 'rindo', 'riso',
                      'lançamento', 'laureado', 'laurel', 'louros', 'pródigo', 'legal', 'conduzir', 'líder', 'liga',
                      'aprender', 'aprendizagem', 'conferencista', 'deriva', 'legal', 'legalizado', 'lendário',
                      'legibilidade', 'legível', 'lazer', 'vagaroso', 'lema', 'clemente', 'lição', 'letrado', 'nível',
                      'influência', 'liberal', 'libertar', 'libertação', 'liberdade', 'biblioteca', 'seiva', 'farol',
                      'gosto', 'linguista', 'leão', 'ágil', 'lógico', 'longevidade', 'senhor', 'senhoria', 'adorável',
                      'Ame',
                      'adorável', 'fazer amor', 'amante', 'amoroso', 'leal', 'lealdade', 'sorte', 'por sorte', 'melado',
                      'brilho', 'lustroso', 'luxuriante', 'luxuoso', 'luxo', 'lira', 'lírico', 'mágico', 'ímã',
                      'magnetismo',
                      'magnetita', 'magnificência', 'magnífico', 'donzela', 'a Principal', 'esteio', 'majestoso',
                      'majestade', 'principal', 'maioria', 'gerir', 'gestão', 'mandarim', 'masculinidade',
                      'manifestado',
                      'viril', 'maná', 'rebuscado', 'maneiras', 'fabricante', 'Março', 'marcado', 'vendável', 'marquês',
                      'casamento', 'medula', 'casar', 'marechal', 'maravilha', 'maravilhoso', 'maravilhosamente',
                      'masculino', 'massagem', 'mestre', 'Obra-prima', 'mestria', 'companheiro', 'maternal',
                      'matrimônio',
                      'matrona', 'máximo', 'prefeito', 'prado', 'medido', 'medalha', 'mediar', 'mediação', 'mediador',
                      'médico', 'meditar', 'Mediterrâneo', 'miscelânea', 'memento', 'memorável', 'reparação',
                      'menstruação',
                      'mentor', 'misericordioso', 'misericórdia', 'fundir', 'mérito', 'meritório', 'folguedo', 'alegre',
                      'metropolitano', 'impetuosidade', 'microscopia', 'parteira', 'obstetrícia', 'poderoso', 'mimo',
                      'atento', 'atenção', 'ministério', 'milagre', 'milagroso', 'alegria', 'missionário', 'modelo',
                      'moderado', 'mediador', 'modesto', 'modéstia', 'ímpeto', 'monetário', 'dinheiro', 'monge',
                      'monumento',
                      'moral', 'moralidade', 'moral', 'argamassa', 'mãe', 'maternidade', 'motivo', 'móvel', 'motor',
                      'caneca', 'muscular', 'música', 'musical', 'mutável', 'mútuo', 'sesta', 'naturalista',
                      'navegável',
                      'ordenadamente', 'néctar', 'agulha', 'negociar', 'negociador', 'vizinho', 'nervo', 'aninhar',
                      'nobreza', 'nobre', 'nobre', 'nomeação', 'normalidade', 'notável', 'notáveis', 'notado', 'noção',
                      'notoriedade', 'nutrição', 'números', 'enfermeira', 'berçário', 'nutrir', 'nutritivo', 'carvalho',
                      'oásis', 'juramento', 'obediência', 'objetivo', 'prestativo', 'observador', 'obtenível', 'óbvio',
                      'ocupante', 'ocupação', 'ocupar', 'oferta', 'oficial', 'compensar', 'ramificação', 'onipotência',
                      'onisciente', 'abertura', 'ópera', 'oportuno', 'oportunidade', 'otimismo', 'otimista', 'opção',
                      'opcional', 'oráculo', 'oração', 'orquestra', 'ordenado', 'ordenado', 'ordenação', 'orgânico',
                      'organização', 'organizar', 'organizado', 'orgasmo', 'originalidade', 'ornamentada',
                      'ornamentado',
                      'explosão', 'resultado', 'sobrepujar', 'excelente', 'para fora', 'radiante', 'esmagador',
                      'propriedade', 'pacífico', 'almofada', 'preenchimento', 'remo', 'saboroso', 'paliativo',
                      'panaceia',
                      'penacho', 'panier', 'páprica', 'desfile', 'parangona', 'supremo', 'parafrasear', 'perdão',
                      'ascendência', 'parietal', 'participar', 'participação', 'parceiro', 'parceria', 'paixão',
                      'apaixonado', 'passatempo', 'pastor', 'pastelaria', 'pasto', 'patente', 'paciência', 'paciente',
                      'patriarcal', 'patrono', 'patrocínio', 'pagar', 'Paz', 'pacífico', 'pacífico', 'pavão', 'bicada',
                      'peculiaridade', 'ascendência', 'inigualável', 'inclinação', 'perceber', 'perceptível', 'perene',
                      'perfeito', 'perfeição', 'executante', 'privilégio', 'permissão', 'perpetuidade', 'persistência',
                      'persistente', 'apresentável', 'pertinente', 'petróleo', 'farmacêutico', 'filantropo',
                      'filantropia',
                      'filósofo', 'Phoenix', 'fonético', 'médico', 'física', 'fisiologia', 'físico', 'escolher',
                      'piquenique', 'pitoresco', 'piedade', 'pílula', 'travesseiro', 'piloto', 'pináculo', 'pioneiro',
                      'piedoso', 'âmago', 'articulação', 'plácido', 'planejamento', 'brincalhão', 'recreio', 'teatro',
                      'agradável', 'satisfeito', 'agradável', 'penhor', 'plenário', 'abundante', 'plexo', 'ameixa',
                      'prumo',
                      'pelúcia', 'dobra', 'vincadamente', 'polícia', 'policial', 'polonês', 'polido', 'educado',
                      'polidez',
                      'político', 'piscina', 'papa', 'popularidade', 'popularizada', 'população', 'portátil', 'possuir',
                      'potável', 'potência', 'poderoso', 'poderosamente', 'prática', 'praticado', 'prática', 'louvor',
                      'elogiou', 'louvável', 'rezar', 'precaução', 'preceder', 'precedência', 'precioso', 'preciso',
                      'precisão', 'predileção', 'predominante', 'preeminente', 'preferir', 'premier', 'local',
                      'preparar',
                      'preparado', 'presciente', 'presença', 'presente', 'apresentável', 'apresentação', 'preservativo',
                      'preservar', 'presidente', 'prestígio', 'presto', 'bonita', 'prevalecer', 'prevenção',
                      'impagável',
                      'orgulho', 'padre', 'sacerdócio', 'sacerdotal', 'primazia', 'primário', 'primordial', 'cartilha',
                      'príncipe', 'principesco', 'Princesa', 'diretor', 'primitivo', 'privilegiado', 'probidade',
                      'procedimento', 'procissão', 'procurador', 'adquirir', 'pródigo', 'prodigioso', 'prodígio',
                      'produtor',
                      'produtor', 'Produção', 'produtivo', 'produtividade', 'profissão', 'profissional', 'professor',
                      'proficiência', 'proficiente', 'profuso', 'progresso', 'progressão', 'progressivo', 'prolífico',
                      'proeminência', 'destaque', 'promessa', 'promissor', 'promoção', 'escorar', 'adequado', 'profeta',
                      'profilático', 'proposição', 'prospecto', 'prosperar', 'prosperidade', 'próspero', 'proteger',
                      'proteção', 'protetor', 'protetor', 'orgulhoso', 'provar', 'proverbial', 'fornecer', 'fornecendo',
                      'prudência', 'prudente', 'salmo', 'público', 'Puxe', 'púlpito', 'pontual', 'pontualidade',
                      'cachorrinho', 'puramente', 'purificação', 'purificar', 'purista', 'pureza', 'ronronar',
                      'singular',
                      'qualificado', 'de qualificação', 'busca', 'pergunta', 'rapidez', 'quiescente', 'quieto',
                      'quinina',
                      'citação', 'esplendor', 'radiante', 'irradiar', 'rádio', 'extasiado', 'arrebatamento', 'racional',
                      'delírio', 'leitor', 'prontamente', 'prontidão', 'leitura', 'reafirmar', 'real', 'razão',
                      'resseguro',
                      'tranqüilizar', 'desconto', 'refundir', 'recebido', 'receber', 'recherche', 'reciprocar',
                      'recuperação', 'reclinar', 'reconhecível', 'recomendar', 'reconciliação', 'reconsideração',
                      'reconstruir', 'reconstrução', 'gravador', 'conservar', 'recuperação', 'recreação', 'recreativo',
                      'retificar', 'redenção', 'reparação', 'refinar', 'requinte', 'reforma', 'reforma', 'reformador',
                      'refrescante', 'renovar', 'régio', 'regente', 'regressivo', 'regularidade', 'regular',
                      'reabilitar',
                      'reabilitação', 'reembolsar', 'reembolso', 'reforço', 'reintegrar', 'regozijar-se', 'regozijo',
                      'rejuvenescer', 'rejuvenescido', 'reacender', 'relaxamento', 'relevante', 'confiabilidade',
                      'confiável', 'confiança', 'alívio', 'aliviando', 'permanece', 'refazer', 'notável',
                      'notavelmente',
                      'remédio', 'remissão', 'remodelar', 'renascimento', 'render', 'renovação', 'renovar', 'renovação',
                      'renome', 'famoso', 'reorganizar', 'reparação', 'reembolsar', 'arrepender-se', 'reabastecimento',
                      'repleto', 'repórter', 'repouso', 'representado', 'reprodutivo', 'respeitável', 'resgate',
                      'reserva',
                      'residente', 'resiliente', 'resistente', 'resolutamente', 'recursos', 'respeito',
                      'respeitabilidade',
                      'respeitável', 'respeitoso', 'respeitando', 'cumprimentos', 'pausa', 'resplandecente',
                      'responsável',
                      'responsivo', 'descansar', 'repousante', 'restituição', 'reconstituinte', 'restaurando',
                      'limitação',
                      'recomeço', 'retenção', 'aposentadoria', 'reunião', 'orgia', 'revels', 'reverenciar',
                      'reverência',
                      'reverendo', 'devaneio', 'revisão', 'renascimento', 'reviver', 'revolução', 'revolucionário',
                      'recompensa', 'ritmo', 'rítmico', 'fita', 'riqueza', 'cavaleiro', 'justo', 'legítimo',
                      'acertadamente',
                      'maduro', 'amadurecer', 'Aumentar', 'fascinante', 'roadster', 'robusto', 'Rocha', 'haste',
                      'brincalhão', 'romance', 'romântico', 'romantismo', 'sapatão', 'enraizado', 'rosado', 'rota',
                      'rotina',
                      'realeza', 'rubrica', 'ruth', 'seguro', 'salvaguardar', 'sálvia', 'santo', 'santo', 'salário',
                      'saliente', 'salutar', 'saudação', 'salvação', 'pomada', 'samurai', 'santificação', 'santificar',
                      'santuário', 'sanguíneo', 'sanitário', 'cetim', 'satisfatoriamente', 'satisfeito', 'salvar',
                      'poupança', 'sabor', 'saboroso', 'experiente', 'espantalho', 'estudioso', 'bolsa de estudo',
                      'científico', 'cientista', 'centelha', 'Ponto', 'escriba', 'escrita', 'delicioso', 'escultura',
                      'mar',
                      'selo', 'temperado', 'isolamento', 'secretariado', 'antiguidade', 'sensacional', 'sentido',
                      'sensibilidade', 'sensatamente', 'sensual', 'sensualidade', 'sensual', 'sentimental',
                      'sentimentalidade', 'sentinela', 'serenidade', 'sermão', 'soro', 'instituidor', 'sexo', 'forma',
                      'bem feito', 'compartilhar', 'abrigo', 'pastor', 'brilho', 'brilhante', 'compras', 'ombro',
                      'sagaz',
                      'seda', 'simplificar', 'sincero', 'sinceridade', 'cantar', 'isoladamente', 'senhor', 'irmandade',
                      'hábil', 'hábil', 'céu', 'ardósia', 'lustroso', 'delgado', 'fino', 'sorriso', 'sorridente',
                      'desbaratados', 'suavidade', 'relincho', 'sobriedade', 'sociável', 'consolo', 'soldado', 'sólido',
                      'solidez', 'solução', 'solvência', 'sonar', 'sonata', 'soneto', 'sonoro', 'acalmar', 'calmante',
                      'classificador', 'solidez', 'sopa', 'estância termal', 'espaçoso', 'spaniel', 'centelha',
                      'especial',
                      'espécie', 'espetáculo', 'discurso', 'célere', 'ortografia', 'especiaria', 'espinha', 'espírito',
                      'espíritos', 'esplêndido', 'esplendor', 'patrocinador', 'imaculado', 'cônjuge', 'asseado',
                      'estável',
                      'staccato', 'inoxidável', 'garanhão', 'robusto', 'vigor', 'de pé', 'estrela', 'luz das estrelas',
                      'estrelado', 'imponente', 'declaração', 'estátua', 'estado', 'acérrimo', 'firme', 'estelar',
                      'esterlino', 'mordomo', 'quietude', 'loja', 'franco', 'estratégico', 'estrategista', 'força',
                      'fortalecer', 'fortalecimento', 'impressionante', 'contundentemente', 'fortemente', 'estrutura',
                      'viga', 'estude', 'robusto', 'sublimação', 'substância', 'substantivo', 'suceder', 'sucedendo',
                      'sucesso', 'bem sucedido', 'sucinto', 'suculento', 'suficiência', 'açúcar', 'adequado', 'abafado',
                      'sol', 'ensolarado', 'pôr do sol', 'luz do sol', 'soberbo', 'sobre-humano', 'superior',
                      'superioridade', 'super-homem', 'Super estrela', 'superstição', 'súplica', 'suprimentos',
                      'fornecem',
                      'suportado', 'suporte', 'que apoia', 'supremacia', 'supremo', 'supremamente', 'fiador',
                      'conjetura',
                      'insuperável', 'surpresa', 'cercar', 'agrimensura', 'sobreviver', 'jurar', 'doce', 'amor',
                      'docinho',
                      'Doçura', 'doces', 'rápido', 'nadar', 'simbólico', 'simétrico', 'simetria', 'compreensivo',
                      'simpatia',
                      'sinfonia', 'sincronizar', 'sinérgica', 'sínodo', 'sinônimo', 'tato', 'conto', 'talento',
                      'talismã',
                      'conversa', 'bronzeado', 'tentadora', 'tarefa', 'de bom gosto', 'saboroso', 'ensinar',
                      'professor',
                      'tecnologia', 'adolescentes', 'temperança', 'temperado', 'defensável', 'persistente',
                      'tenacidade',
                      'arrendamento', 'inquilino', 'proposta', 'ternura', 'grato', 'ação de graças', 'teórico',
                      'terapêutico', 'terapêutica', 'pensador', 'com brio', 'pensativo', 'reflexão', 'parcimônia',
                      'emoção',
                      'emocionante', 'próspera', 'trono', 'cócegas', 'revestimento', 'oportuno', 'ouropel', 'título',
                      'torrada', 'tolerante', 'tolerância', 'topo', 'dureza', 'torre', 'altaneiro', 'tradicional',
                      'tranquilo', 'tranqüilidade', 'transcendência', 'transcendental', 'viajando', 'tesouro', 'tratar',
                      'árvore', 'tremendamente', 'tendência', 'trendy', 'afluente', 'tributo', 'trigonometria',
                      'triunfo',
                      'triunfante', 'troféu', 'trégua', 'verdade', 'fiel', 'verdade', 'veracidade', 'tutela', 'tutor',
                      'gêmeo', 'cintilação', 'em última análise', 'árbitro', 'unanimidade', 'unânime', 'modesto',
                      'invicto',
                      'imparcial', 'inquebrável', 'desenfreado', 'intacto', 'sem constrangimento', 'sublinhado',
                      'compreensão', 'subscrever', 'indiviso', 'imortal', 'inequivocamente', 'inesperado', 'desdobrar',
                      'unificação', 'uniformemente', 'inimaginável', 'não infectado', 'único', 'unissonância',
                      'unitário',
                      'unido', 'unidade', 'universidade', 'ilimitado', 'despretensioso', 'incontestável',
                      'inquestionavelmente', 'incontestado', 'ileso', 'desinteressado', 'sem igual', 'desatar', 'firme',
                      'ladeira acima', 'elevação', 'vertical', 'utilidade', 'arrumador', 'usual', 'utilidade',
                      'utópico',
                      'férias', 'vacina', 'valente', 'bravura', 'valioso', 'vanguarda', 'vencer', 'veludo', 'aveludado',
                      'venerável', 'veneração', 'veracidade', 'verdejante', 'verificação', 'verificado', 'na verdade',
                      'verdadeiro', 'vernal', 'verve', 'veterano', 'vigário', 'vencedor', 'vitorioso', 'vitória',
                      'vigilância', 'Vigilância', 'vigor', 'vigoroso', 'aldeão', 'vindicado', 'vindicação', 'virgem',
                      'virgindade', 'virtude', 'virtuoso', 'visão', 'visionário', 'visita', 'visitante', 'vital',
                      'vitalidade', 'vivaz', 'vívido', 'vocabulário', 'voluntário', 'voluptuoso', 'voto', 'atestar',
                      'voto',
                      'salário', 'garantia', 'Guerreiro', 'cão de guarda', 'vigilante', 'vigia', 'riqueza',
                      'resistente',
                      'intempéries', 'peso', 'congratulou', 'branco', 'brancura', 'saudável', 'postigo',
                      'muito difundido',
                      'de bom grado', 'boa vontade', 'herança inesperada', 'vencedora', 'vencedor', 'ganhos', 'sem fio',
                      'wis', 'sabedoria', 'sábio', 'inteligência', 'resistir', 'juízo', 'espirituoso', 'Mago', 'ventre',
                      'maravilhoso', 'maravilhosamente', 'maravilhoso', 'palavra', 'trabalhando', 'adoração',
                      'que vale a pena', 'digno', 'wot', 'escritor', 'ânsia', 'jovem', 'mais jovem', 'juventude',
                      'zelo',
                      'zeloso', 'entusiasmo']

palavras_negativas = ['abandonar', 'abandonado', 'abandono', 'abdução', 'aberrante', 'aberração', 'abominar',
                      'detestável', 'abjeto', 'anormal', 'abolir', 'abolição', 'abominável', 'abominação', 'abortar',
                      'aborto', 'abortivo', 'abrasão', 'revogar', 'abscesso', 'ausência', 'ausente', 'absentista',
                      'absentismo', 'absurdo', 'absurdo', 'abundância', 'Abuso', 'abismal', 'abismo', 'acidente',
                      'acidental', 'amaldiçoado', 'acusação', 'acusativo', 'acusado', 'acusador', 'acusador', 'dor',
                      'doendo', 'ácido', 'litigável', 'víbora', 'vício', 'adiposo', 'adjudicar', 'admoestação',
                      'à deriva', 'adulterada', 'adultério', 'adversário', 'desfavoraveis', 'adversidade', 'afligir',
                      'aflito', 'aflição', 'afronta', 'com medo', 'resultado', 'gosto posterior', 'agravado',
                      'agravante', 'agravamento', 'agressão', 'agressivo', 'agressor', 'horrorizado', 'agitado',
                      'agitação', 'agonizante', 'agonia', 'encalhado', 'afligir', 'doente', 'sem objetivo', 'afetação',
                      'alarme', 'alarmante', 'alcoolismo', 'alienígena', 'alienar', 'alienado', 'alienação',
                      'pensão alimentícia', 'alegação', 'alegar', 'indiferente', 'altercação', 'ambíguo', 'emboscada',
                      'amnésia', 'anfetaminas', 'jibóia', 'anal', 'anarquismo', 'anarquista', 'anarquia', 'anátema',
                      'antigo', 'raiva', 'angina', 'pesca', 'zangado', 'angústia', 'animosidade', 'animosidade',
                      'aniquilar', 'aniquilado', 'aniquilação', 'incomodar', 'aborrecimento', 'irritante', 'anular',
                      'anulação', 'anomalia', 'anônimo', 'antagonismo', 'antagonista', 'antagônico', 'antraz',
                      'anticristo', 'antipatia', 'antiquado', 'anti social', 'antítese', 'ansiedade', 'ansioso',
                      'apache', 'apático', 'apatia', 'afídio', 'apavorante', 'apendicite', 'apreensão', 'apreensivo',
                      'apropriação', 'arcaico', 'árduo', 'discutir', 'argumento', 'argumentativo', 'árido',
                      'armamentos', 'armado', 'acusação', 'atraso', 'prender', 'arrogância', 'arrogante', 'arsênico',
                      'incêndio criminoso', 'artilharia', 'cinza', 'envergonhado', 'cinza', 'burro', 'assaltar',
                      'assaltante', 'assassino', 'assassinar', 'assassinato', 'assalto', 'Idiota', 'extraviar',
                      'adstringente', 'asilo', 'ateísmo', 'aterosclerose', 'atroz', 'atrocidade', 'atrofia', 'ataque',
                      'atacante', 'atenuada', 'atenuação', 'audácia', 'austero', 'austeridade', 'autocrático',
                      'autópsia', 'avalanche', 'avareza', 'vingador', 'adverso', 'aversão', 'evitar', 'anulação',
                      'terrível', 'embaraço', 'errado', 'balbuciar', 'balbucio', 'babuíno', 'para trás', 'para trás',
                      'ressaca', 'bactérias', 'bactéria', 'ruim', 'texugo', 'mal', 'ruindade', 'meirinho', 'isca',
                      'fardo', 'tropeço', 'bálsamo', 'banimento', 'bandido', 'perdição', 'estrondo', 'banger', 'banir',
                      'banido', 'banimento', 'falido', 'falência', 'Banshee', 'farpa', 'bárbaro', 'bárbaro',
                      'barbarismo', 'latido', 'barrado', 'estéril', 'barricada', 'barreira', 'infundado', 'Desgraçado',
                      'bater', 'agredidas', 'bateria', 'batalha', 'batalhou', 'campo de batalha', 'indecente',
                      'baioneta', 'O portador', 'besta', 'bestial', 'espancamento', 'acontecer', 'implorar', 'mendigo',
                      'implorando', 'gigante', 'obrigado', 'atrasado', 'desmerecer', 'beligerante', 'cinto', 'bender',
                      'enlutado', 'perda', 'desolado', 'frenético', 'bestial', 'trair', 'traição', 'ter cuidado',
                      'aturdido', 'viés', 'tendenciosa', 'insignificância', 'esquife', 'intolerante', 'fanático',
                      'bílis', 'biopsia', 'vidoeiro', 'local de nascimento', 'cadela', 'morder', 'amargamente',
                      'amargura', 'bizarro', 'preto', 'blackjack', 'chantagem', 'negrume', 'culpa', 'brando',
                      'blasfemo', 'blasfêmia', 'explosão', 'ruidoso', 'tagarelice', 'labareda', 'desabrigado',
                      'hemorragia', 'defeito', 'ferrugem', 'arruinada', 'cego', 'cegado', 'cegamente', 'cegueira',
                      'bolha', 'inchado', 'gota', 'bloqueio', 'derramamento de sangue', 'sanguinário', 'sangrento',
                      'borrão', 'soprador', 'soprar', 'blues', 'blefe', 'mancada', 'borrão', 'desfocado', 'rubor',
                      'ostentação', 'ostentando', 'pântano', 'falso', 'fervura', 'clichê', 'violento', 'bomba',
                      'bombardear', 'bombardeamento', 'bombardeou', 'escravidão', 'títulos', 'boo', 'pateta', 'traça',
                      'bebida alcoólica', 'diâmetro', 'tédio', 'chato', 'mutuário', 'incomodar', 'incomodando',
                      'inferior', 'limite', 'ataque', 'bovino', 'Garoto', 'boicote', 'vangloriar-se', 'conhaque',
                      'bravata', 'rixa', 'descarado', 'violar', 'demolir', 'arriscado', 'romper', 'suborno', 'suborno',
                      'brigada', 'enxofre', 'cerda', 'bordo', 'grelhar', 'quebrou', 'quebrado', 'bordel', 'equimose',
                      'peso', 'brutal', 'brutalidade', 'brutamontes', 'pinote', 'buffet', 'erro', 'bicho-papão',
                      'bulboso', 'valentão', 'vagabundo', 'vadio', 'oneroso', 'burocracia', 'burocrata', 'assaltante',
                      'roubo', 'enterro', 'enterrado', 'Burke', 'queimado', 'preso', 'açougueiro', 'bumbum', 'zumbiam',
                      'cabala', 'cacofonia', 'gigolô', 'cadáver', 'gaiola', 'cálculo', 'insensível', 'chamadas',
                      'campanha', 'cancelar', 'câncer', 'gangrena', 'canibal', 'canibalismo', 'canhão', 'cativo',
                      'cativeiro', 'captor', 'captura', 'carcaça', 'carcinoma', 'cardiomiopatia', 'descuido',
                      'caricatura', 'cárie', 'carnificina', 'carnal', 'carnívoro', 'cartel', 'caso', 'caixão', 'casta',
                      'acidente', 'catarata', 'catástrofe', 'cateter', 'cautela', 'ceder', 'celebridade', 'cemitério',
                      'censor', 'censura', 'cesso', 'cessação', 'palha', 'atrito', 'desgosto', 'desafio', 'caos',
                      'caótico', 'charada', 'imputável', 'Encantado', 'perseguição', 'castigo', 'tagarela', 'barato',
                      'enganação', 'bolo de queijo', 'chicana', 'infantil', 'frio', 'clorofórmio', 'afogador', 'cólera',
                      'costeleta', 'tarefa', 'crônico', 'cigarro', 'evasão', 'clamor', 'choque', 'colidindo', 'garra',
                      'claustro', 'nublado', 'nebulosidade', 'moita', 'desajeitado', 'cocaína', 'coagir', 'coerção',
                      'caixão', 'frio', 'friamente', 'frieza', 'cólica', 'colapso', 'colisão', 'conluio', 'coma',
                      'comatoso', 'combate', 'combatente', 'combativo', 'compromisso', 'comoção', 'comunismo',
                      'comunista', 'concorrência', 'queixar-se', 'queixa', 'complexado', 'complexidade', 'complicar',
                      'complicado', 'complicação', 'cumplicidade', 'adubo', 'compulsão', 'obrigatório', 'esconder',
                      'oculto', 'dissimulação', 'presunção', 'vaidoso', 'concussão', 'condenar', 'condenação',
                      'condescendente', 'condescendência', 'confessar', 'confissão', 'confinar', 'confinado',
                      'reclusão', 'confiscar', 'confisco', 'conflagração', 'conflito', 'contraditório', 'confundir',
                      'desconcertado', 'confundir', 'confusão', 'congestionamento', 'conjurando', 'conquista',
                      'conspirador', 'conspirar', 'consternação', 'prisão de ventre', 'constranger', 'constrangido',
                      'restrição', 'contágio', 'contagioso', 'contaminar', 'contaminado', 'contaminação', 'desprezo',
                      'desprezível', 'desdenhoso', 'contencioso', 'contrabando', 'contraído', 'contradizer',
                      'contradição', 'contraditório', 'contrário', 'contrastava', 'infringir', 'contravenção',
                      'controverso', 'controvérsia', 'presidiário', 'convicção', 'gaiola', 'cópia', 'imitador',
                      'médico legista', 'corporal', 'cadáver', 'correção', 'corrosão', 'corrosivo', 'corrupto',
                      'corruptora', 'corrupção', 'tosse', 'conselheiro', 'que percorre', 'cobiçar', 'covarde',
                      'covardia', 'covardemente', 'ranzinza', 'fenda', 'rachado', 'craqueamento', 'cãibra',
                      'espasmódico', 'manivela', 'adoentado', 'porcaria', 'colisão', 'rastejamento', 'louco', 'louco',
                      'ranger', 'criatura', 'rastejar', 'crime', 'criminal', 'criminalidade', 'adular servilmente',
                      'aleijado', 'aleijado', 'crise', 'quebradiço', 'crítico', 'crítica', 'criticar', 'trapaceiro',
                      'Cruz', 'agachado', 'cruciforme', 'crucificação', 'bruto', 'cruel', 'cruelmente', 'crueldade',
                      'desmoronando', 'crise', 'cruzada', 'esmagado', 'esmagador', 'rabugento', 'chora', 'chorando',
                      'cripta', 'corno', 'cuco', 'refugo', 'culpabilidade', 'culpável', 'culpado', 'culto', 'pesado',
                      'astuto', 'sangria', 'vira-lata', 'maldição', 'amaldiçoado', 'maldição', 'apressado', 'cortador',
                      'assassino', 'corte', 'cianeto', 'ciclone', 'cisto', 'citomegalovírus', 'intrometendo', 'demônio',
                      'maluco', 'punhal', 'dano', 'danos', 'Droga', 'danação', 'condenado', 'amortecedor', 'caspa',
                      'dândi', 'perigo', 'perigoso', 'escurecer', 'escurecido', 'escuridão', 'pontilhada', 'covarde',
                      'atordoada', 'desativar', 'impasse', 'mortal', 'surdo', 'morte', 'desastre', 'deboche',
                      'detritos', 'dívida', 'devedor', 'decadência', 'deteriorado', 'falecido', 'engano', 'enganador',
                      'enganar', 'enganado', 'iludindo', 'engano', 'enganoso', 'declinação', 'declínio', 'declinante',
                      'decomposição', 'diminuir', 'diminuição', 'decrépito', 'desacreditar', 'subtrair', 'difamação',
                      'difamatório', 'padrão', 'derrota', 'derrotado', 'defeito', 'deserção', 'defeituoso',
                      'sem defesa', 'diferimento', 'desafio', 'desafiador', 'deficiência', 'déficit', 'esvaziar',
                      'deflação', 'deformar', 'deformado', 'deformidade', 'defraudar', 'defunto', 'desafiar',
                      'degeneração', 'degenerado', 'degradação', 'degradar', 'aviltante', 'atraso', 'atrasado',
                      'deletério', 'eliminação', 'delinquência', 'delinquente', 'delirante', 'delírio', 'dilúvio',
                      'ilusão', 'delirante', 'exigem', 'exigente', 'demente', 'demência', 'falecimento', 'demolir',
                      'demolição', 'demônio', 'demoníaco', 'desmoralizado', 'negação', 'negado', 'denunciar',
                      'denúncia', 'negar', 'negando', 'partiu', 'partida', 'dependência', 'dependência', 'dependente',
                      'deplorável', 'deplorar', 'deportar', 'deportação', 'depravado', 'depravação', 'depreciar',
                      'depreciados', 'depreciação', 'deprimir', 'deprimido', 'deprimente', 'depressão', 'depressivo',
                      'privação', 'demente', 'abandonado', 'escárnio', 'derrogação', 'depreciativo', 'profanação',
                      'deserto', 'deserto', 'deserção', 'desistir', 'desolação', 'desespero', 'desesperando',
                      'desesperado', 'desprezível', 'desprezar', 'despótico', 'despotismo', 'desamparado', 'destruído',
                      'destruidor', 'destruidor', 'destruição', 'destrutivo', 'destacamento', 'deter', 'detento',
                      'detenção', 'deteriorar', 'deteriorou-se', 'deterioração', 'detestar', 'detonar', 'diminuir',
                      'detrimento', 'prejudicial', 'detrito', 'devastar', 'devastador', 'devastação', 'diabo',
                      'diabólico', 'desonesto', 'devolução', 'devorar', 'diabólico', 'diagnóstico', 'diatribe',
                      'ditador', 'ditatorial', 'ditadura', 'morrer', 'dificuldades', 'dificuldade', 'divagar',
                      'dilapidado', 'diluir', 'diminuir', 'diminuído', 'estrondo', 'horrendo', 'sujeira', 'sujo',
                      'incapacidade', 'incapacitar', 'Desativado', 'desafeto', 'discordar', 'discordando', 'desacordo',
                      'não permitido', 'desiludir', 'desapontado', 'decepcionante', 'desapontamento', 'desaprovação',
                      'desaprovar', 'desaprovava', 'desaprovando', 'desastre', 'desastroso', 'descrer', 'devoluções',
                      'quitação', 'disciplina', 'renunciar', 'descoloração', 'descolorido', 'desconforto', 'desligar',
                      'desligado', 'desconexão', 'descontentamento', 'descontinuar', 'descontinuidade', 'discórdia',
                      'desencorajar', 'desencorajamento', 'desacreditar', 'discriminar', 'discriminador',
                      'discriminação', 'desdém', 'doença', 'doente', 'desencarnada', 'desimpedimento', 'desfigurado',
                      'desgraça', 'desonrado', 'vergonhoso', 'descontente', 'desgosto', 'repugnante', 'desmotivada',
                      'desanimador', 'desonesto', 'desonestidade', 'desonra', 'desilusão', 'desinformação', 'insincero',
                      'desintegrar', 'desintegração', 'desinteressado', 'antipatia', 'não gostou', 'deslocado',
                      'sombrio', 'desânimo', 'desmembramento', 'demissão', 'desobediência', 'desobediente',
                      'desobedecer', 'desordem', 'desordenado', 'desorganizado', 'denegrir', 'depreciativo',
                      'disparidade', 'imparcial', 'dissipar', 'dispersão', 'deslocar', 'Descontente',
                      'descontentamento', 'disposição', 'despossuídos', 'disputa', 'desqualificação', 'desqualificado',
                      'desqualificar', 'negligência', 'desconsiderada', 'desonroso', 'desrespeito', 'desrespeitoso',
                      'rompimento', 'descontentamento', 'dissensão', 'contrário', 'desserviço', 'dissidente',
                      'dissolução', 'dissonância', 'desgosto', 'desagradável', 'distorcida', 'distorção', 'distrair',
                      'distraído', 'distracção', 'distração', 'perturbado', 'aflição', 'angustiado', 'aflitivo',
                      'desconfiança', 'perturbação', 'perturbado', 'desuso', 'desafectada', 'divergente', 'diverso',
                      'alienadas', 'desinvestimento', 'divórcio', 'tontura', 'tonto', 'ancorado', 'faça', 'calmarias',
                      'doação', 'dor', 'dominante', 'dominar', 'dominação', 'asno', 'rabisco', 'destruição',
                      'condenado', 'Dia do julgamento', 'dúvida', 'duvidoso', 'duvidoso', 'ducha', 'severo', 'ruína',
                      'monótono', 'drenagem', 'recua', 'pavor', 'terrível', 'terrivelmente', 'triste', 'bebendo',
                      'baba', 'zangão', 'drooping', 'seca', 'afogar', 'sonolência', 'labuta', 'bêbado', 'embriaguez',
                      'duvidoso', 'embotar', 'burro', 'manequim', 'dumps', 'pardo', 'calabouço', 'joguete',
                      'duplicidade', 'coação', 'poeira', 'anão', 'morrendo', 'disenteria', 'terremoto', 'espionagem',
                      'édito', 'efeminado', 'egoísta', 'egrégio', 'ejetar', 'ejeção', 'eliminação', 'esquivo',
                      'emaciado', 'embargo', 'embaraçar', 'embaraçoso', 'embaraço', 'desfalque', 'embolia', 'enredado',
                      'emergência', 'enclave', 'invasão', 'estorvo', 'pôr em perigo', 'endangered', 'endêmico',
                      'interminável', 'inimigo', 'fazer cumprir', 'aplicação', 'enigmático', 'inimizade', 'escravizar',
                      'escravizados', 'escravização', 'enredado', 'emaranhamento', 'entranhas', 'invejoso', 'epidemia',
                      'epilepsia', 'erradicar', 'erradicação', 'apagar', 'erosão', 'erótico', 'errar', 'errante',
                      'errático', 'errata', 'errôneo', 'erro', 'entrar em erupção', 'erupção', 'escalar', 'fuga',
                      'evitar', 'espionagem', 'distante', 'eutanásia', 'evacuar', 'evacuação', 'evadir', 'evasão',
                      'expulsar', 'despejo', 'mal', 'exacerbar', 'exacerbação', 'exigente', 'exagerar', 'exagerado',
                      'exame', 'exasperação', 'escavação', 'excesso', 'imposto', 'excluídos', 'Excluindo', 'exclusão',
                      'excremento', 'excruciante', 'desculpa', 'execução', 'carrasco', 'escape', 'esgotado', 'exaustão',
                      'exigente', 'exílio', 'exorcismo', 'expatriado', 'expelir', 'despesa', 'despesas', 'expirar',
                      'expirado', 'expletivo', 'explodir', 'explosão', 'explosivo', 'exposto', 'expropriação',
                      'expulsão', 'exterminar', 'exterminação', 'extinto', 'extinguir', 'extrajudicial', 'extremidade',
                      'fabricar', 'fabricação', 'desvanecer', 'fezes', 'falta', 'falha', 'desmaio', 'Sem fé',
                      'falsificação', 'outono', 'falaz', 'falácia', 'falível', 'queda', 'alqueive', 'falsidade',
                      'falsamente', 'falsificação', 'falsificar', 'falsidade', 'vacilar', 'fome', 'fanático', 'farsa',
                      'burlesco', 'jejum', 'gordura', 'fatal', 'fatalidade', 'destino', 'fadiga', 'fatigado',
                      'gorduroso', 'falha', 'defeituoso', 'gamo', 'medo', 'temeroso', 'medrosamente', 'temendo',
                      'febril', 'fecal', 'fezes', 'taxa', 'débil', 'sentindo-me', 'fingido', 'caiu', 'criminoso',
                      'crime', 'fermento', 'feroz', 'ferocidade', 'feudo', 'feudal', 'feudalismo', 'febril', 'fiasco',
                      'gracejar', 'inconstante', 'fictício', 'demônio', 'feroz', 'luta', 'luta', 'flibusteiro',
                      'imundície', 'imundo', 'armas de fogo', 'encaixa', 'flácido', 'flácido', 'sinalização',
                      'flagrante', 'floco', 'aba', 'flatulência', 'ostentar', 'falha', 'pulga', 'fugir', 'velo',
                      'carnudo', 'vacilar', 'flerte', 'açoitar', 'fiasco', 'linguado', 'gripe', 'flutuação', 'inimigo',
                      'frustrou', 'loucura', 'enganar', 'tolo', 'loucura', 'forragem', 'incursão', 'proibir',
                      'ameaçador', 'vigor', 'forçado', 'forçosamente', 'presságio', 'excluir', 'renunciar',
                      'estrangeiro', 'estrangeiro', 'prevenido', 'confiscar', 'confiscados', 'confisco', 'falsificação',
                      'esqueço', 'esquecido', 'desamparado', 'informe', 'fornicação', 'abandonar', 'desamparado',
                      'falta', 'fratura', 'frágil', 'fragilidade', 'frenético', 'fraude', 'fraudulento', 'cheio',
                      'briga', 'desgastado', 'bizarro', 'congelando', 'frenético', 'frenético', 'frenesi', 'fricção',
                      'susto', 'assustar', 'assustado', 'assustador', 'frígido', 'frívolo', 'congelamento', 'espuma',
                      'carranca', 'carrancudo', 'infrutífero', 'frustrar', 'frustrado', 'frustração', 'lorota',
                      'fugitivo', 'inépcia', 'fumo', 'fumegando', 'fungo', 'medo', 'furioso', 'furor', 'fúria',
                      'espalhafato', 'espalhafatoso', 'fútil', 'futilidade', 'tolo', 'mordaça', 'fel', 'forca', 'jogar',
                      'jogador', 'jogos de azar', 'gangue', 'prisão', 'lacuna', 'lixo', 'berrante', 'enfeite', 'talho',
                      'ofegando', 'acanhado', 'magro', 'cavalheiro', 'geriátrica', 'medonho', 'gueto', 'fantasmagórico',
                      'algaravia', 'glacial', 'brilho intenso', 'flagrante', 'loquaz', 'melancolia', 'sombrio',
                      'sorumbático', 'excesso', 'gula', 'gnomo', 'gnomo', 'ateu', 'gonorréia', 'goo', 'escornar',
                      'desfiladeiro', 'gorila', 'sangrento', 'fofoca', 'goiva', 'gota', 'governo', 'agarrar', 'ávido',
                      'grelha', 'ralado', 'grade', 'grave', 'cobiça', 'ganancioso', 'granada', 'aflição', 'agravo',
                      'afligir', 'grave', 'severo', 'sujeira', 'encardido', 'esmerilhamento', 'macabro', 'grisalho',
                      'gemido', 'tatear', 'bruto', 'grotesco', 'fundamentado', 'infundado', 'rosnar', 'rosnando',
                      'rancor', 'de má vontade', 'macabro', 'áspero', 'resmungar', 'mal humorado', 'guerrilha',
                      'malícia', 'guilhotina', 'culpa', 'culpado', 'aparência', 'gaivota', 'crédulo', 'pistola',
                      'jorro', 'guzzling', 'cigano', 'bruxa', 'desfigurado', 'saudar', 'peludo', 'a meio caminho',
                      'alucinação', 'cabresto', 'hesitante', 'dificultar', 'jarretar', 'desvantagem', 'enforcamento',
                      'carrasco', 'molestar', 'prenúncio', 'endurecido', 'dureza', 'dificuldade', 'meretriz', 'dano',
                      'prejudicial', 'pungente', 'harry', 'aspereza', 'de hash', 'haxixe', 'apressado', 'odiar',
                      'detestável', 'odiando', 'ódio', 'altivo', 'assombro', 'assombrada', 'destruição', 'perigo',
                      'perigoso', 'neblina', 'dor de cabeça', 'inebriante', 'audição', 'boato', 'carro fúnebre',
                      'mágoa', 'azia', 'sem coração', 'pagão', 'pesadamente', 'hedonismo', 'calcanhar', 'aumentar',
                      'hediondo', 'inferno', 'infernal', 'desamparado', 'desamparo', 'hemorragia', 'hemorróidas',
                      'heresia', 'herege', 'hermafrodita', 'heroína', 'herpes', 'herpesvírus', 'hesitação', 'oculto',
                      'hediondo', 'mais alta', 'dificultando', 'obstáculo', 'hippie', 'assobio', 'assobio', 'bater',
                      'até agora', 'colméia', 'rouco', 'grisalho', 'engano', 'vagabundo', 'porco', 'oco', 'holocausto',
                      'sem casa', 'com saudades de casa', 'homicida', 'homicídio', 'homossexualidade', 'capuz', 'curvo',
                      'vaia', 'sem esperança', 'desespero', 'horda', 'horrível', 'horrivelmente', 'horrível',
                      'horrível', 'horrorizado', 'horripilante', 'horror', 'horrores', 'refém', 'hostil',
                      'hostilidades', 'hostilidade', 'uivo', 'xingar', 'humilde', 'mistificação', 'humilhar',
                      'humilhante', 'humilhação', 'pressentimento', 'faminto', 'caçador', 'caça', 'furacão',
                      'apressado', 'ferido', 'prejudicial', 'machucando', 'pessoa ativa', 'hidra', 'hidrocefalia',
                      'campanha publicitária', 'hipérbole', 'hipocrisia', 'hipócrita', 'hipócrita', 'histeria',
                      'histérico', 'idiotia', 'idiota', 'idiota', 'pessoa ociosa', 'idolatria', 'ignorância',
                      'ignorante', 'ignorar', 'doente', 'ilegal', 'ilegalidade', 'ilegível', 'ilegítimo', 'ilícito',
                      'analfabeto', 'doença', 'ilógico', 'ilusão', 'imitado', 'imitação', 'imaturo', 'imaturidade',
                      'imediatamente', 'imoral', 'imoralidade', 'imóvel', 'prejudicar', 'Prejuízo', 'intransitável',
                      'impaciência', 'impaciente', 'acusar', 'impugnação', 'impedir', 'imperfeição', 'imperfeitamente',
                      'personificar', 'representação', 'implacável', 'implicar', 'descortês', 'imposição', 'impossível',
                      'impotência', 'impotente', 'represar', 'impraticável', 'aprisionar', 'preso', 'prisão',
                      'impropriedade', 'imprudente', 'impuro', 'impureza', 'imputação', 'incapacidade', 'inacessível',
                      'impreciso', 'em ação', 'inatividade', 'inadequação', 'inadequado', 'inadmissível', 'fútil',
                      'inaplicável', 'inadequado', 'negligência', 'inaudível', 'incalculável', 'incapacidade',
                      'encarceramento', 'em caso', 'incendiário', 'incenso', 'incessante', 'incesto', 'incestuoso',
                      'incineração', 'incitar', 'inclemente', 'incoerente', 'renda', 'incompatível', 'incompetência',
                      'incompetente', 'incompletude', 'incompreensível', 'incongruente', 'sem importância',
                      'inconsiderado', 'inconsistência', 'inconveniente', 'incorreta', 'incrédulo', 'incriminação',
                      'pesadelo', 'incorrer em', 'incurável', 'incursão', 'indecente', 'indecisão', 'indeciso',
                      'indefensável', 'indenizar', 'recorte', 'indeterminado', 'acusar', 'acusação', 'indiferença',
                      'indigente', 'indignado', 'indignação', 'indistinto', 'doutrinação', 'indolente', 'ineficaz',
                      'ineficaz', 'ineficiência', 'ineficiente', 'inepto', 'ineptidão', 'desigualdade', 'injusto',
                      'inerte', 'indesculpável', 'inexperiência', 'inexperiente', 'inexplicável', 'infame', 'infâmia',
                      'infanticídio', 'infantil', 'infarto', 'infectar', 'infecção', 'infeccioso', 'inferior',
                      'inferioridade', 'inferno', 'infertilidade', 'infestação', 'infiel', 'infidelidade',
                      'infiltração', 'enfermo', 'enfermidade', 'inflamação', 'inflado', 'inflação', 'infligir',
                      'inflição', 'influência', 'gripe', 'informador', 'infração', 'com pouca freqüência', 'violação',
                      'inibir', 'inóspito', 'desumano', 'desumanidade', 'hostil', 'iniquidade', 'injunção', 'ferir',
                      'ferido', 'prejudicial', 'prejuízo', 'injustiça', 'habitante', 'inoperante', 'insano',
                      'insanidade', 'inseguro', 'insegurança', 'insidioso', 'insignificância', 'insignificante',
                      'insípido', 'insolente', 'insolvência', 'insolvente', 'instabilidade', 'instigar', 'instigação',
                      'insuficiência', 'insuficiente', 'insuficientemente', 'insulto', 'insultuoso', 'insurgente',
                      'intransponível', 'insurreição', 'intenso', 'entre', 'interdição', 'interferência', 'enterro',
                      'interminável', 'interromper', 'interrompeu', 'intervenção', 'intestado', 'intimidar',
                      'intimidação', 'intolerável', 'intolerância', 'intolerante', 'embriagado', 'intratável',
                      'intriga', 'intruso', 'intrusão', 'intrusivo', 'invadir', 'invasor', 'invalidar', 'invalidação',
                      'invalidez', 'invasão', 'involuntário', 'involução', 'enfurecido', 'ira', 'ferros', 'irracional',
                      'irracionalidade', 'irreconciliável', 'irregular', 'irregularidade', 'irrelevante', 'irreparável',
                      'irresponsável', 'irreverente', 'irrevogável', 'irritabilidade', 'irritável', 'irritante',
                      'irritação', 'isolado', 'isolamento', 'tagarelar', 'cadeia', 'jargão', 'chocante', 'icterícia',
                      'ciumento', 'ciúme', 'pôr em perigo', 'perigo', 'João', 'piada', 'Jornada', 'confusão', 'lixo',
                      'junta', 'juvenil', 'kern', 'pontapé', 'raptar', 'matar', 'matança', 'pipa', 'dobre a finados',
                      'nodoso', 'trabalhado', 'laborioso', 'labirinto', 'renda', 'falta', 'sem', 'desbotado',
                      'carregado', 'atraso', 'atraso', 'covil', 'lamento', 'desmoronamento', 'lânguido', 'definhar',
                      'lânguido', 'lapso', 'roubo de coisas miúdas', 'chicote', 'tarde', 'atraso', 'latente',
                      'latrinas', 'risível', 'lava', 'ilegalidade', 'ação judicial', 'advogado', 'frouxo', 'laxante',
                      'preguiçoso', 'vazamento', 'vazamento', 'que vaza', 'sair', 'sanguessuga', 'sanguessugas', 'leer',
                      'limão', 'lepra', 'lésbica', 'diminuir', 'menor', 'letal', 'letargia', 'leucemia', 'arrecadação',
                      'lascivo', 'ligação', 'mentiroso', 'difamação', 'liberal', 'lambida', 'mentira', 'sem vida',
                      'limitado', 'mancar', 'fibra de algodão', 'licor', 'apático', 'litigante', 'litigar', 'litígio',
                      'litigioso', 'ninhada', 'lívido', 'pão', 'vadio', 'relutante', 'detestar', 'repugnância',
                      'repugnante', 'lobista', 'trancar', 'gafanhoto', 'alto', 'solidão', 'solitário', 'solitário',
                      'loo', 'lágrima', 'mergulhão', 'tolo', 'pilhagem', 'senhor', 'perder', 'a perderem', 'perda',
                      'perdido', 'sonoridade', 'salão', 'piolho', 'diminuir', 'baixa', 'menor', 'planícies', 'humilde',
                      'ridículo', 'pesado', 'protuberância', 'grumoso', 'loucura', 'lunático', 'guinada', 'isca',
                      'lúgubre', 'espreitar', 'à espreita', 'luxuriante', 'luxúria', 'concupiscente', 'mentindo',
                      'linchar', 'clava', 'louco', 'enlouquecer', 'louco', 'loucura', 'máfia', 'larva', 'improvisado',
                      'doença', 'mal-estar', 'malária', 'malevolente', 'prevaricação', 'malformação', 'malícia',
                      'malicioso', 'maligno', 'malignidade', 'maligno', 'malversação', 'despacho', 'sarna', 'calandra',
                      'mania', 'maníaco', 'maníaco', 'manipular', 'manipulação', 'homicídio involuntário', 'estrume',
                      'estragar', 'margem', 'castanho-avermelhado', 'gamarra', 'mártir', 'martírio', 'masoquismo',
                      'massacre', 'materialismo', 'materialista', 'maternal', 'Meandros', 'sem sentido', 'sarampo',
                      'intrometer-se', 'medíocre', 'mediocridade', 'melancólico', 'melancolia', 'refrega', 'melodrama',
                      'fusão', 'ameaça', 'ameaçador', 'servil', 'mercenário', 'impiedoso', 'confusão', 'confuso',
                      'metástase', 'metanol', 'parteira', 'míldio', 'milícia', 'mimetismo', 'minimizar', 'mínimo',
                      'minoria', 'lama', 'mau comportamento', 'aborto espontâneo', 'travessura', 'pernicioso',
                      'equívoco', 'mau comportamento', 'miserável', 'miseravelmente', 'miséria', 'infortúnio',
                      'extraviado', 'acidente', 'interpretação errada', 'induzir em erro', 'enganador',
                      'má administração', 'descasamento', 'termo impróprio', 'misplace', 'extraviado', 'deturpar',
                      'deturpação', 'deturpado', 'ausência de', 'distorção', 'erro', 'enganado', 'amante',
                      'desconfiança', 'entender mal', 'mal-entendido', 'abuso', 'ácaro', 'máfia', 'zombaria',
                      'zombeteiro', 'molestação', 'monocromático', 'monopolista', 'monção', 'monstro', 'monstruosidade',
                      'temperamental', 'discutível', 'mórbido', 'morbidez', 'morgue', 'moribundo', 'Idiota', 'imbecil',
                      'bocado', 'mortal', 'mortalidade', 'mortificação', 'mortuário', 'mosquito', 'mãe', 'chorar',
                      'pesaroso', 'luto', 'estrumar', 'lama', 'trapalhada', 'confusa', 'lamacento', 'regalo', 'caneca',
                      'mula', 'mãe', 'resmungar', 'caxumba', 'assassinato', 'assassino', 'assassino', 'escuro',
                      'confusão', 'mofado', 'mutante', 'mutilado', 'mutilação', 'amotinação', 'resmungar', 'focinho',
                      'miopia', 'prender', 'nadir', 'cavalo', 'ingênuo', 'sem nome', 'nappy', 'narcótico',
                      'desagradável', 'danadinho', 'náusea', 'nauseabundo', 'ou melhor', 'necessário', 'carente',
                      'nefasto', 'negação', 'negativo', 'negligência', 'negligenciadas', 'negligenciando',
                      'negligência', 'negligente', 'negligentemente', 'negro', 'nepotismo', 'nervoso', 'inferior',
                      'urtiga', 'neuralgia', 'neurose', 'neurótico', 'nicotina', 'nigger', 'pesadelo', 'niilismo',
                      'ruído', 'barulhento', 'descumprimento', 'disparate', 'sem sentido', 'armadilha', 'nada',
                      'notoriedade', 'nocivo', 'incómodo', 'nul', 'anular', 'entorpecido', 'entorpecimento', 'freira',
                      'imbecil', 'obeso', 'obesidade', 'obi', 'obit', 'obituário', 'objeção', 'censurável', 'obrigar',
                      'devedor', 'obliterar', 'obliterado', 'obliteração', 'esquecimento', 'desagradável', 'obsceno',
                      'obscenidade', 'obscuridade', 'obstáculo', 'obstinado', 'obstruir', 'obstrução', 'obstrutivo',
                      'obtuso', 'oculto', 'esquisitice', 'odioso', 'odor', 'ofender', 'ofendido', 'ofensor', 'ofensa',
                      'ofensivo', 'improvisadamente', 'offing', 'ogro', 'olfatório', 'oligarquia', 'presságio',
                      'ameaçador', 'omitir', 'onipotência', 'oneroso', 'ônus', 'lodo', 'opaco', 'operística', 'opiáceo',
                      'teimoso', 'ópio', 'adversário', 'opor-se', 'contrário', 'oposição', 'oprimir', 'opressão',
                      'opressivo', 'opressor', 'orc', 'provação', 'artilharia', 'órfão', 'ostensivamente', 'expulsar',
                      'explosão', 'exilado', 'clamor', 'telheiro', 'estranho', 'proscrever', 'ultraje', 'excelente',
                      'ovação', 'arrogante', 'sobrecarregar', 'escuro', 'exagerar', 'overdose', 'atrasado',
                      'superestimada', 'transbordamento', 'coberto', 'sobrecarga', 'pago em excesso', 'dominar',
                      'avassalador', 'superfaturada', 'fiscalização', 'derrubada', 'derrubar', 'oprimir',
                      'sobrecarregado', 'que é devido', 'oxidação', 'dor', 'triste', 'doloroso', 'dolorosamente',
                      'dores', 'paralisia', 'pandemia', 'aflição', 'pânico', 'desfile', 'paralisia', 'paralisado',
                      'paranóia', 'parafrasear', 'parasita', 'aparar', 'papagaio', 'parcimonioso', 'partidário',
                      'fora de moda', 'passiva', 'passividade', 'remendo', 'patético', 'paternalista', 'tamborilar',
                      'escassez', 'indigente', 'penhor', 'retorno', 'pagamento', 'peculiaridades', 'pedestre', 'penal',
                      'pena', 'penetração', 'penitenciária', 'perdição', 'perigo', 'perigoso', 'perecer', 'perecível',
                      'pereceram', 'que perece', 'perjúrio', 'pernicioso', 'perpetrador', 'perpetuação', 'perplexo',
                      'perplexidade', 'perseguir', 'perseguição', 'perturbação', 'pertussis', 'perverso', 'perversão',
                      'perverter', 'pervertido', 'pessimismo', 'pessimista', 'praga', 'peste', 'animal de estimação',
                      'petróleo', 'pequeno', 'fantasma', 'fleuma', 'falso', 'piquete', 'picketing', 'salmoura', 'porco',
                      'Pombo', 'hemorróidas', 'pilhagem', 'cafetão', 'espinha', 'pinho', 'pinhão', 'melindre',
                      'pirataria', 'pirata', 'pistola', 'armadilha', 'plágio', 'praga', 'querelante', 'banhado',
                      'jogador', 'apelo', 'apuro', 'pesado', 'prumo', 'pilhagem', 'mergulho', 'pneumonia',
                      'caça furtiva', 'pointless', 'veneno', 'envenenado', 'intoxicação', 'venenoso', 'cotovelada',
                      'polêmica', 'polio', 'poluir', 'poluição', 'poligamia', 'pompa', 'pomposo', 'pesado',
                      'pobremente', 'estouro', 'porco-espinho', 'pornô', 'porno', 'pornográfico', 'pornografia', 'pose',
                      'possesso', 'posse', 'póstumo', 'adiamento', 'libra', 'pobreza', 'impotente', 'brincadeira',
                      'precário', 'recinto', 'predatório', 'predicamento', 'gravidez', 'prejuízo', 'preconceituoso',
                      'prejudicial', 'premeditado', 'apresentação', 'pressão', 'presunçoso', 'fingir', 'fingido',
                      'fingindo', 'pretensão', 'pretensões', 'preventivo', 'presa', 'picada', 'espinhoso', 'prisão',
                      'prisioneiro', 'latrina', 'problema', 'procrastinar', 'Procrastinação', 'pródigo', 'profano',
                      'profanidade', 'profusão', 'proibido', 'proibição', 'prolongar', 'promíscuo', 'propaganda',
                      'processar', 'acusação', 'prostituta', 'prostituição', 'provocação', 'provocante', 'alavanca',
                      'prying', 'psicose', 'publicista', 'ofegante', 'soco', 'pungente', 'punir', 'punido', 'punindo',
                      'punição', 'punitivo', 'purgatório', 'purga', 'pus', 'charlatão', 'atoleiro', 'codorniz',
                      'dilema', 'desavença', 'anular', 'reprimir', 'questionável', 'mercúrio', 'desistir', 'aljava',
                      'estremecimento', 'questionário', 'citação', 'ralé', 'fanático', 'raiva', 'cremalheira',
                      'raquete', 'radiação', 'radioativo', 'radão', 'raiva', 'furioso', 'trapos', 'incursão', 'trilho',
                      'RAM', 'desconexo', 'alvoroço', 'rançoso', 'resgate', 'estupro', 'raptors', 'patife',
                      'erupção cutânea', 'rato', 'classificação', 'rouco', 'delírio', 'voraz', 'delirante',
                      'reacionário', 'traseiro', 'rebelde', 'repreensão', 'refutar', 'recalcitrante', 'recessão',
                      'reincidência', 'imprudente', 'imprudência', 'redundante', 'refluxo', 'refratário', 'recusa',
                      'recusar', 'recusada', 'regressar', 'regressão', 'regressivo', 'arrepender', 'lamentável',
                      'lamentava', 'Lamentando', 'regulamentar', 'rédea', 'rejeitar', 'rejeitados', 'rejeição',
                      'rejeita', 'reacender', 'recaída', 'relegação', 'abandonar', 'relutante', 'permanece',
                      'reencarceramento', 'curativo', 'remisso', 'remorso', 'remoção', 'remover', 'chocar-se', 'rasgar',
                      'renegado', 'renunciar', 'renúncia', 'repelente', 'repelente', 'repelindo', 'reprimir',
                      'repressão', 'reprimenda', 'reimpressão', 'represália', 'censura', 'república', 'repúdio',
                      'repulsão', 'rescindir', 'rescisão', 'ressentir', 'ressentido', 'ressentimento', 'demitir-se',
                      'demissão', 'resignado', 'resistir', 'resistência', 'resistente', 'resistindo', 'conter',
                      'restringir', 'restrição', 'restritivo', 'retaliar', 'retaliação', 'retaliativo', 'retardar',
                      'retardo', 'reticente', 'aposentadoria', 'retorta', 'retrair', 'retratação', 'cerceamento',
                      'retribuição', 'retrógrado', 'vingança', 'reversão', 'reviver', 'revogação', 'revogar', 'revolta',
                      'revoltante', 'revolução', 'revólver', 'asco', 'reumatismo', 'raquítico', 'crivado', 'ridículo',
                      'ridículo', 'freqüente', 'rifle', 'fenda', 'rígido', 'rigidez', 'rigor', 'rigoroso', 'campainha',
                      'revolta', 'turbulento', 'risco', 'arriscado', 'rivalidade', 'roubar', 'ladrão', 'roubo',
                      'trapaceiro', 'torre', 'podridão', 'apodrecendo', 'rugosidade', 'derrota', 'linha', 'turbulento',
                      'lixo', 'pedregulho', 'arruda', 'irritar', 'áspero', 'ruína', 'arruinado', 'ruinoso', 'rumor',
                      'fugir', 'ruptura', 'estratagema', 'ferrugem', 'enferrujado', 'impiedoso', 'sabre', 'sabotar',
                      'sacrifícios', 'tristemente', 'tristeza', 'decair', 'seiva', 'sarcasmo', 'sarcoma', 'sardônico',
                      'satânico', 'saturado', 'selvagem', 'selvageria', 'sarna', 'andaime', 'bisturi', 'com escamas',
                      'escândalo', 'escandaloso', 'escasso', 'bode expiatório', 'cicatriz', 'escasso', 'mal',
                      'escassez', 'susto', 'espantalho', 'limpador', 'esquema', 'cisma', 'esquizofrenia', 'ciática',
                      'zombar', 'repreender', 'repreensão', 'abrasador', 'desprezo', 'escorpião', 'escocês', 'canalha',
                      'flagelo', 'embaralhamento', 'scrapie', 'gritar', 'gritando', 'guincho', 'aparafusado',
                      'escaramuça', 'esfrega', 'escrutinar', 'escrutínio', 'escumalha', 'cauterizar', 'secessão',
                      'isolado', 'isolamento', 'usado', 'secreção', 'secreto', 'sectário', 'sedição', 'seduzir',
                      'sedução', 'separar', 'segregado', 'apreender', 'egoísta', 'egoísmo', 'senil', 'sem sentido',
                      'sensual', 'sentença', 'separatista', 'sepsia', 'séptico', 'seqüestro', 'sereno', 'serpente',
                      'servo', 'servir', 'servil', 'servidão', 'revés', 'cortar', 'esgoto', 'rede de esgotos', 'gasto',
                      'cabana', 'manilha', 'com sombra', 'sacudindo', 'trêmulo', 'impostura', 'matadouro', 'vergonha',
                      'vergonhoso', 'desavergonhado', 'Xangai', 'Tubarão', 'quebrar', 'destruído', 'verter', 'Concha',
                      'engavetado', 'naufrágio', 'merda', 'arrepio', 'choque', 'de qualidade inferior', 'atirar',
                      'tiroteio', 'furto em lojas', 'escassez', 'deficiência', 'tiro', 'empurrão', 'vistoso', 'guincho',
                      'estridente', 'encolher', 'encolhido', 'estremecimento', 'esquivar-se a', 'doente', 'repugnante',
                      'doentio', 'doença', 'bobo', 'pecado', 'pecaminoso', 'sinistro', 'pecador', 'pecando', 'sereia',
                      'maricas', 'cético', 'esboçado', 'enviesada', 'derrapagem', 'pular', 'escaramuça', 'negligente',
                      'escória', 'batida', 'calúnia', 'calunioso', 'tapa', 'chacina', 'matadouro', 'abate', 'escravo',
                      'escravidão', 'matar', 'matador', 'chuva com neve', 'viscoso', 'escapulir', 'deslize', 'poça',
                      'desleixado', 'preguiça', 'desleixo', 'lamaçal', 'lentidão', 'lodo', 'lesma', 'lento', 'favela',
                      'crise', 'estigma', 'baboseira', 'cadela', 'manhoso', 'beijoca', 'pequeno', 'quebra', 'esmagado',
                      'conhecimento limitado', 'cheiro', 'cheirando', 'sorrir afetadamente', 'desbaratar', 'fumante',
                      'sufocar', 'mancha', 'presunçoso', 'contrabandear', 'contrabandista', 'contrabando',
                      'obscenidade', 'protuberância', 'senões', 'serpente', 'laço', 'rosnado', 'rosnando',
                      'esgueirar-se', 'furtivo', 'zombaria', 'espirrar', 'falsificado', 'esnobe', 'embeber', 'soluço',
                      'socialista', 'solo', 'sujado', 'somático', 'sombrio', 'fuligem', 'feitiçaria', 'sórdido',
                      'dolorido', 'extremamente', 'dor', 'tristeza', 'triste', 'sortida', 'desumano', 'alma gêmea',
                      'azedo', 'palmada', 'espasmo', 'ovas', 'lança', 'partícula', 'espetáculo', 'espectro',
                      'espectral', 'especulação', 'gasto', 'espinha', 'solteirona', 'despeito', 'rancoroso', 'lasca',
                      'Dividido', 'splitting', 'estragar', 'Spoiler', 'falou', 'esponja', 'fantasma', 'entorse',
                      'farra', 'duende', 'espúrio', 'borrasca', 'squatter', 'enjoado', 'esmagar', 'contorcer-se',
                      'facada', 'cambaleando', 'estagnado', 'mancha', 'rançoso', 'talo', 'impasse', 'paralisação',
                      'encarando', 'forte', 'assustar', 'fome', 'Starved', 'fome', 'estacionário', 'aduela', 'roubar',
                      'roubo', 'furtivo', 'estereótipo', 'estereotipado', 'estéril', 'esterilidade', 'esterlino',
                      'popa', 'rígido', 'rigidez', 'sufocar', 'sufocada', 'estigma', 'nascido morto', 'ferrão',
                      'pungente', 'mesquinho', 'fedor', 'fedorento', 'restrição', 'estoques', 'roubado', 'pedra',
                      'apedrejado', 'fezes', 'paragem', 'tempestade', 'tormentoso', 'tenso', 'estreito', 'encalhado',
                      'desconhecido', 'estrangular', 'stray', 'estresse', 'luta', 'greve', 'faixa', 'listra',
                      'despojado', 'golpe', 'luta', 'escorar', 'abafado', 'tropeçar', 'atordoado', 'atrofiado',
                      'estúpido', 'estupidez', 'estupor', 'chiqueiro', 'subjugar', 'assunto', 'submetido', 'sujeição',
                      'subjugação', 'subordinado', 'intimação', 'abaixamento', 'subsídio', 'subsistir', 'subtrair',
                      'subversão', 'subversivo', 'subverter', 'suculento', 'sucumbir', 'chupar', 'aproveitador',
                      'processar', 'sofrer', 'sofredor', 'sofrimento', 'asfixiante', 'sufocação', 'suicida', 'suicídio',
                      'taciturno', 'convocação', 'afundado', 'superficial', 'supérfluo', 'superstição', 'supersticioso',
                      'suprimir', 'supressão', 'supremacia', 'sobretaxa', 'grosseiro', 'rendição', 'rendição', 'cercar',
                      'suscetível', 'suspeito', 'suspensão', 'suspeita', 'suspeito', 'cotonete', 'pântano', 'pantanoso',
                      'suástica', 'inchaço', 'gole', 'suíno', 'inchado', 'sintoma', 'síncope', 'sinônimo', 'tabu',
                      'mácula', 'garras', 'emaranhado', 'tentadora', 'atraso', 'tardio', 'tarifa', 'embaçar',
                      'alcatroado', 'insípido', 'sarcasmo', 'imposto', 'provocação', 'provocação', 'tedioso', 'tédio',
                      'adolescentes', 'tempestade', 'tentação', 'casa de habitação', 'terminal', 'terminação',
                      'térmite', 'terrível', 'terror', 'terrorismo', 'terrorista', 'aterrorizar', 'tétano', 'corrente',
                      'roubo', 'teísmo', 'teocrático', 'ladrao', 'sedento', 'espinho', 'espinhoso', 'irrefletido',
                      'açoitar', 'ameaça', 'ameaçar', 'ameaçador', 'debulhar', 'pulsar', 'regulador de pressão',
                      'bandido', 'baque', 'trovejante', 'frustrar', 'arrufo', 'tímido', 'timidez', 'embriagado',
                      'invectiva', 'cansado', 'cansaço', 'cansativo', 'cavalinho', 'sapo', 'tabaco', 'banheiro',
                      'armadilha', 'tolerar', 'dor de dente', 'tormento', 'rasgado', 'torpedo', 'tórrido', 'dano',
                      'tortious', 'tortura', 'tocado', 'suscetível', 'difícil', 'tóxico', 'toxina', 'tragédia',
                      'trágico', 'traidor', 'vagabundo', 'transe', 'transgressão', 'pompa', 'armadilhas', 'lixo',
                      'inútil', 'traumático', 'dores de parto', 'caricatura', 'traiçoeiro', 'traição', 'traição',
                      'tratar', 'trêmulo', 'tremor', 'trepidação', 'transgressão', 'tribulação', 'tribunal', 'truque',
                      'trapaça', 'bagatela', 'tropeçar', 'cantarolar', 'perturbador', 'trombeta', 'queda', 'tumor',
                      'tumor', 'tumulto', 'tumultuoso', 'turbulência', 'turbulento', 'tumulto', 'contorcer', 'tufão',
                      'tirânico', 'tirania', 'tirano', 'feiúra', 'feio', 'úlcera', 'ulterior', 'ultimato', 'incapaz',
                      'inaceitável', 'inexplicável', 'não aprovado', 'independente', 'irrealizável', 'pouco atraente',
                      'não autorizado', 'inevitável', 'inconsciente', 'insuportável', 'invicto', 'descrença',
                      'inacreditável', 'por nascer', 'desenfreado', 'misterioso', 'uncaring', 'incerto', 'imutável',
                      'imundo', 'desconfortável', 'injusto', 'inconsciente', 'inconstitucional', 'incontrolável',
                      'descontrolado', 'indeciso', 'minado', 'mal pago', 'demasiado pequeno', 'indesejável',
                      'indesejada', 'desfazer', 'inquietação', 'inquieto', 'ignorante', 'desempregado', 'desigual',
                      'desigual', 'inesperado', 'inexplicável', 'Injusto', 'injustiça', 'infiel', 'desfavorável',
                      'inacabado', 'imperdoável', 'infeliz', 'hostil', 'por cumprir', 'sem mobília', 'ímpio', 'ingrato',
                      'infelicidade', 'infeliz', 'pouco saudável', 'profano', 'inimaginável', 'sem importância',
                      'unimpressed', 'não melhorado', 'não informado', 'não iniciados', 'sem inspiração',
                      'ininteligível', 'involuntariamente', 'desinteressado', 'desinteressante', 'injusto',
                      'injustificável', 'injustificada', 'grosseiro', 'desconhecido', 'ilegal', 'sem licença',
                      'azarado', 'ingovernável', 'antinatural', 'não oficial', 'não remunerado', 'desagradável',
                      'impopular', 'imprevisível', 'despreparado', 'improdutivo', 'não rentável', 'desprotegido',
                      'inédito', 'não confiável', 'não correspondido', 'indisciplinado', 'inseguro', 'não satisfatório',
                      'insatisfeito', 'desagradável', 'sem escrúpulos', 'incerto', 'sem graça', 'simples', 'indizível',
                      'instável', 'sem êxito', 'impróprio', 'não celebrado', 'sem suporte', 'insustentável',
                      'insensível', 'não domesticado', 'insustentável', 'impensável', 'desordenado', 'desatar',
                      'intempestivo', 'sem título', 'incalculável', 'desagradável', 'inexperiente', 'falso',
                      'desonesto', 'injustificável', 'sujo', 'indesejável', 'indisposto', 'falta de vontade',
                      'imprudente', 'involuntário', 'indigno', 'inflexível', 'sublevação', 'ladeira acima',
                      'insurreição', 'tumulto', 'chateado', 'diabrete', 'urgente', 'inútil', 'usurpar', 'usurpado',
                      'usura', 'vaga', 'vazio', 'vago', 'vagueza', 'em vão', 'vampiro', 'desaparecido', 'vaidade',
                      'varicela', 'varicoso', 'vegetativo', 'veemente', 'vendeta', 'vingança', 'vingativo', 'veneno',
                      'peçonhento', 'verbosidade', 'beira', 'bicharada', 'versus', 'vertigem', 'veto', 'vício',
                      'vicioso', 'vítima', 'vitimados', 'vilão', 'vil', 'vingativo', 'violação', 'violência',
                      'violento', 'violentamente', 'víbora', 'virulência', 'vírus', 'visitação', 'megera',
                      'volatilidade', 'vulcão', 'vómitos', 'vodu', 'voto', 'vulgar', 'vulgaridade', 'vulnerabilidade',
                      'abutre', 'waffle', 'lamúria', 'aguarde', 'chafurdar', 'pálido', 'declínio', 'querendo', 'guerra',
                      'diretor', 'louça', 'guerra', 'bélico', 'advertir', 'urdidura', 'deformado', 'verruga',
                      'desperdício', 'desperdiçado', 'desperdiçador', 'desperdiçando', 'aguado', 'vacilar',
                      'enfraquecido', 'fracamente', 'fraqueza', 'usar', 'wearily', 'cansaço', 'cansado',
                      'ervas daninhas', 'chorar', 'peso', 'esquisito', 'esquisitão', 'wen', 'meretriz', 'bater',
                      'capricho', 'choramingar', 'chicote', 'redemoinho de vento', 'uísque', 'prostituta', 'perverso',
                      'maldade', 'selvagem', 'gato selvagem', 'wildfire', 'intencional', 'banana', 'fracote',
                      'estremecimento', 'bruxa', 'feitiçaria', 'retirar', 'murchar', 'murchou', 'aflição', 'mísero',
                      'lamentavelmente', 'palavras', 'verme', 'usado', 'preocupado', 'preocupar-se', 'preocupante',
                      'pior', 'piora', 'sem valor', 'ferida', 'questiúnculas', 'ira', 'desafogar', 'naufrágio',
                      'naufragado', 'chave', 'luta', 'desgraçado', 'miserável', 'errado', 'transgressão', 'ilegal',
                      'erradamente', 'forjado', 'torto', 'xenofobia', 'bocejo', 'bocejando', 'ânsia', 'gritar',
                      'amarelos', 'ganido', 'zip']

stopwords = ['de', 'a', 'o', 'que', 'e', 'do', 'da', 'em', 'um', 'para', 'é', 'com', 'não', 'uma', 'os', 'no', 'se',
             'na', 'por', 'mais', 'as', 'dos', 'como', 'mas', 'foi', 'ao', 'ele', 'das', 'tem', 'à', 'seu', 'sua', 'ou',
             'ser', 'quando', 'muito', 'há', 'nos', 'já', 'está', 'eu', 'também', 'só', 'pelo', 'pela', 'até', 'isso',
             'ela', 'entre', 'era', 'depois', 'sem', 'mesmo', 'aos', 'ter', 'seus', 'quem', 'nas', 'me', 'esse', 'eles',
             'estão', 'você', 'tinha', 'foram', 'essa', 'num', 'nem', 'suas', 'meu', 'às', 'minha', 'têm', 'numa',
             'pelos', 'elas', 'havia', 'seja', 'qual', 'será', 'nós', 'tenho', 'lhe', 'deles', 'essas', 'esses',
             'pelas', 'este', 'fosse', 'dele', 'tu', 'te', 'vocês', 'vos', 'lhes', 'meus', 'minhas', 'teu', 'tua',
             'teus', 'tuas', 'nosso', 'nossa', 'nossos', 'nossas', 'dela', 'delas', 'esta', 'estes', 'estas', 'aquele',
             'aquela', 'aqueles', 'aquelas', 'isto', 'aquilo', 'estou', 'está', 'estamos', 'estão', 'estive', 'esteve',
             'estivemos', 'estiveram', 'estava', 'estávamos', 'estavam', 'estivera', 'estivéramos', 'esteja',
             'estejamos', 'estejam', 'estivesse', 'estivéssemos', 'estivessem', 'estiver', 'estivermos', 'estiverem',
             'hei', 'há', 'havemos', 'hão', 'houve', 'houvemos', 'houveram', 'houvera', 'houvéramos', 'haja', 'hajamos',
             'hajam', 'houvesse', 'houvéssemos', 'houvessem', 'houver', 'houvermos', 'houverem', 'houverei', 'houverá',
             'houveremos', 'houverão', 'houveria', 'houveríamos', 'houveriam', 'sou', 'somos', 'são', 'era', 'éramos',
             'eram', 'fui', 'foi', 'fomos', 'foram', 'fora', 'fôramos', 'seja', 'sejamos', 'sejam', 'fosse', 'fôssemos',
             'fossem', 'for', 'formos', 'forem', 'serei', 'será', 'seremos', 'serão', 'seria', 'seríamos', 'seriam',
             'tenho', 'tem', 'temos', 'tém', 'tinha', 'tínhamos', 'tinham', 'tive', 'teve', 'tivemos', 'tiveram',
             'tivera', 'tivéramos', 'tenha', 'tenhamos', 'tenham', 'tivesse', 'tivéssemos', 'tivessem', 'tiver',
             'tivermos', 'tiverem', 'terei', 'terá', 'teremos', 'terão', 'teria', 'teríamos', 'teriam']
